# Generated by Django 3.2.7 on 2022-02-18 16:23

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=64, null=True, verbose_name='Район')),
                ('street', models.CharField(max_length=64, verbose_name='Улица')),
                ('mark', models.CharField(max_length=64, verbose_name='Марка авто')),
                ('model', models.CharField(max_length=64, verbose_name='Модель авто')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('start_date', models.DateField(verbose_name='Начало сдачи')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец сдачи')),
                ('term', models.CharField(max_length=64, verbose_name='Срок')),
                ('carcase', models.CharField(max_length=64, verbose_name='Кузов')),
                ('_class', models.CharField(max_length=64, verbose_name='Класс')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('created', models.DateField(default=datetime.date(2022, 2, 18), verbose_name='Дата создания')),
                ('engine', models.CharField(max_length=64, verbose_name='Двигатель')),
                ('power', models.CharField(max_length=64, verbose_name='Мощность')),
                ('drive', models.CharField(max_length=64, verbose_name='Привод')),
                ('color', models.CharField(max_length=64, verbose_name='Цвет')),
                ('mildeage', models.CharField(max_length=64, verbose_name='Пробег')),
                ('rudder', models.CharField(max_length=64, verbose_name='Положение руля')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.profile')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название марки')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(verbose_name='Позитивный отзыв')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created', models.DateField(default=datetime.date(2022, 2, 18), verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.profile', verbose_name='Автор')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='jwt_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 2, 18), verbose_name='Дата создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='jwt_auth.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название модели')),
                ('start_year', models.IntegerField(verbose_name='Старт производства')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='Окончание производства')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sent', models.DateTimeField(default=datetime.datetime(2022, 2, 18, 16, 23, 6, 751328))),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to='jwt_auth.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChangePasswordTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_password', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=4)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeEmailTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=4)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.get_file_path, verbose_name='Изображение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
            ],
            options={
                'verbose_name': 'Изображение автомобиля',
                'verbose_name_plural': 'Изображения автомобилей',
            },
        ),
    ]
