# Generated by Django 3.2.7 on 2022-02-19 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateField(default=datetime.date(2022, 2, 19), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 8, 43, 46, 352599)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 19), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(default=datetime.date(2022, 2, 19), verbose_name='Дата создания'),
        ),
    ]
