# Generated by Django 3.2.7 on 2022-02-20 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220220_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepasswordtemp',
            name='confirmation_type',
            field=models.CharField(default='email', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 20, 13, 3, 12154)),
        ),
    ]
