# Generated by Django 3.2.9 on 2022-02-24 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220220_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='название списка')),
            ],
            options={
                'verbose_name': 'Список/категория',
                'verbose_name_plural': 'Списки и категории',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateField(default=datetime.date(2022, 2, 24), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 22, 49, 21, 972297)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 24), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(default=datetime.date(2022, 2, 24), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, verbose_name='значение')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.list')),
            ],
            options={
                'verbose_name': 'Элемент списка',
                'verbose_name_plural': 'Элементы списка',
            },
        ),
    ]
