# Generated by Django 3.2.9 on 2022-02-24 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_message_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='название настройки')),
                ('value', models.CharField(max_length=256, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Найстройки',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 22, 59, 18, 265896)),
        ),
    ]
