# Generated by Django 3.2.7 on 2022-02-19 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(default=datetime.date(2022, 2, 19), verbose_name='Дата регистрации'),
        ),
    ]
