# Generated by Django 3.2.9 on 2022-02-24 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_alter_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(default=datetime.date(2022, 2, 24), verbose_name='Дата регистрации'),
        ),
    ]
